/* Generated By:JJTree: Do not edit this line. ASTassignationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTassignationExpression extends SimpleNode {
  public ASTassignationExpression(int id) {
    super(id);
  }

  public ASTassignationExpression(LOL p, int id) {
    super(p, id);
  }
 
  String name;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1bcd94972f259f8d6683fd874034b9b0 (do not edit this line) */
