/* Generated By:JJTree: Do not edit this line. ASTbinaryOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

import ca.polymtl.lol.BinaryOpType;

public
class ASTbinaryOperator extends SimpleNode {
  public ASTbinaryOperator(int id) {
    super(id);
  }

  public ASTbinaryOperator(LOL p, int id) {
    super(p, id);
  }
  
  BinaryOpType type;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e71d3816ac3e364d4ee831198f8e1aef (do not edit this line) */
