/* Generated By:JJTree: Do not edit this line. ASTcastExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTcastExpression extends SimpleNode {
  public ASTcastExpression(int id) {
    super(id);
  }

  public ASTcastExpression(LOL p, int id) {
    super(p, id);
  }

  enum Type { STRING, BOOLEAN, NOTYPE, FLOAT, INTEGER};
  
  Type type;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be39437426d7a535ae2ba63247ffc498 (do not edit this line) */
