/* Generated By:JJTree: Do not edit this line. ASTconsoleOutput.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTconsoleOutput extends SimpleNode {
  public ASTconsoleOutput(int id) {
    super(id);
  }

  public ASTconsoleOutput(LOL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a447a05c762ed03b6ae2eb711f8d1777 (do not edit this line) */
