/* Generated By:JJTree: Do not edit this line. ASTconsoleInput.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTconsoleInput extends SimpleNode {
  public ASTconsoleInput(int id) {
    super(id);
  }

  public ASTconsoleInput(LOL p, int id) {
    super(p, id);
  }

  String variable;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=19b9cdb6b3c69dfb69fb0554bd81185f (do not edit this line) */
