/* Generated By:JJTree: Do not edit this line. ASTdefaultBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTdefaultBlock extends SimpleNode {
  public ASTdefaultBlock(int id) {
    super(id);
  }

  public ASTdefaultBlock(LOL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bea45bd3bc8433d5ff4cb9fb9e72b8a9 (do not edit this line) */
