/* Generated By:JJTree: Do not edit this line. ASTfunctionDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

import java.util.*;

public
class ASTfunctionDefinition extends SimpleNode {
  public ASTfunctionDefinition(int id) {
    super(id);
  }

  public ASTfunctionDefinition(LOL p, int id) {
    super(p, id);
  }

  public String name;
  public Vector<String> params = new Vector<String>();

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
 
}
/* JavaCC - OriginalChecksum=f57dc6fa276ef4ca7be8fada895a427d (do not edit this line) */
