/* Generated By:JJTree: Do not edit this line. ASTheader.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTheader extends SimpleNode {
  public ASTheader(int id) {
    super(id);
  }

  public ASTheader(LOL p, int id) {
    super(p, id);
  }

  String version;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b6855ed4dfed13a532a26c56ba31848e (do not edit this line) */
