/* Generated By:JJTree: Do not edit this line. ASTliteralValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTliteralValue extends SimpleNode {
  public ASTliteralValue(int id) {
    super(id);
  }

  public ASTliteralValue(LOL p, int id) {
    super(p, id);
  }

  public enum LiteralType { STRING, DECIMAL, BOOLEAN, FLOAT }

  public String value;
  public LiteralType type;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4013dbd923afc0002394793b0e6b9486 (do not edit this line) */
