/* Generated By:JJTree: Do not edit this line. ASTloopExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

import ca.polymtl.lol.LoopLimit;
import ca.polymtl.lol.LoopOperation;

public
class ASTloopExpression extends SimpleNode {
  public ASTloopExpression(int id) {
    super(id);
  }

  public ASTloopExpression(LOL p, int id) {
    super(p, id);
  }

  public LoopLimit loopLimit;
  
  String name;
  public String loopVariable;
  
  public LoopOperation operation;
  public String customOperation;
  
  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=54e88a3a6fbb4c64e2e0bfca3cb05c5c (do not edit this line) */
