/* Generated By:JJTree: Do not edit this line. ASTswitchExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ca.polymtl.lol.grammar;

public
class ASTswitchExpression extends SimpleNode {
  public ASTswitchExpression(int id) {
    super(id);
  }

  public ASTswitchExpression(LOL p, int id) {
    super(p, id);
  }

  public boolean hasDefault = false;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=899bb66e2cf1ca84aef74e5f015f6969 (do not edit this line) */
