/* Generated By:JJTree: Do not edit this line. ASTvariableOrFunctionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package ca.polymtl.lol.grammar;

public
class ASTvariableOrFunctionExpression extends SimpleNode {
  public ASTvariableOrFunctionExpression(int id) {
    super(id);
  }

  public ASTvariableOrFunctionExpression(LOL p, int id) {
    super(p, id);
  }

  public String name;
  public int nbArgs;

  /** Accept the visitor. **/
  @Override
public Object jjtAccept(LOLVisitor visitor, Object data) throws LOLVisitException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ba11def6ca759a12792716afcdc31d8 (do not edit this line) */
