/* Generated By:JavaCC: Do not edit this line. LOLVisitor.java Version 4.1 */
package ca.polymtl.lol.grammar;

public interface LOLVisitor
{
  public Object visit(SimpleNode node, Object data) throws LOLVisitException;
  public Object visit(ASTliteralValue node, Object data) throws LOLVisitException;
  public Object visit(ASTunaryOperator node, Object data) throws LOLVisitException;
  public Object visit(ASTbinaryOperator node, Object data) throws LOLVisitException;
  public Object visit(ASTinfiniteArityOperator node, Object data) throws LOLVisitException;
  public Object visit(ASTvariableOrFunctionExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTcastExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTprimaryExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTvariableDeclaration node, Object data) throws LOLVisitException;
  public Object visit(ASTconsoleOutput node, Object data) throws LOLVisitException;
  public Object visit(ASTconsoleInput node, Object data) throws LOLVisitException;
  public Object visit(ASTthenBlock node, Object data) throws LOLVisitException;
  public Object visit(ASTelseIfBlock node, Object data) throws LOLVisitException;
  public Object visit(ASTelseBlock node, Object data) throws LOLVisitException;
  public Object visit(ASTconditionalExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTcaseBlock node, Object data) throws LOLVisitException;
  public Object visit(ASTdefaultBlock node, Object data) throws LOLVisitException;
  public Object visit(ASTswitchExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTloopExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTassignationExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTcastVariableExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTfunctionDefinition node, Object data) throws LOLVisitException;
  public Object visit(ASTbreakExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTreturnExpression node, Object data) throws LOLVisitException;
  public Object visit(ASTstart node, Object data) throws LOLVisitException;
}
/* JavaCC - OriginalChecksum=b07760c18b8f6ff74be0427a1a7308f0 (do not edit this line) */
